### DISCUSSION TITLE
suricata repeat mode

### DISCUSSION THREAD

**Discussion by volga629-1** [FoobarOy/foomuuri#80] [General]
Hello Everyone,
I am looking if possible set action on packet if detected by suricata in NFQ ---> repeat mode.
Right now packet mirrored to internal interface which suricata doing processing and repeat should return it back, but I can't detect packet with foomuuri

Any help thank you 

```
nfq:
  mode: repeat
  repeat-mark: 1
  repeat-mask: 1
  bypass-mark: 1
  bypass-mask: 1
  route-queue: 5
  fail-open: yes
```
