### DISCUSSION TITLE
Using Foomuuri Macros for a More Integrated QoS Setup

### DISCUSSION THREAD

**Discussion by Joao0026** [FoobarOy/foomuuri#87] [General]
Hello everyone,

I'd like to share the work I recently developed as part of a curricular internship, focused on creating a more robust and flexible Quality of Service (QoS) system for the Foomuuri Firewall, using tc (HTB). This led me to explore different ways to manage the QoS configuration, and I'd appreciate some feedback or discussion on the approach.

**Goal:**
The objective was to implement granular QoS with HTB for both upload and download, allowing rate/ceil limits and priorities per service (identified by a Foomuuri mark), with the crucial ability to define different limits for the same service on different WAN interfaces (Multi-WAN scenario).

**Initial Thoughts & The Macro Question:**
My initial thought, inspired by Shorewall's structure and aiming for maximum integration, was whether Foomuuri's macro system could be leveraged to define the entire QoS policy (interfaces, total bandwidths, default classes, service definitions with upload/download limits, and per-interface overrides).

However, I quickly ran into perceived limitations:

* Representing nested structures (like service -> interface -> upload/download -> rate/ceil) seemed very complex and potentially unreadable using the current macro syntax.
* Parsing such a complex structure from macros within an external script (like the Python one needed to apply tc rules) appeared significantly more difficult and error-prone than parsing a standard configuration format like YAML.

**Final Solution: External YAML + Python Script + Foomuuri Marking**
Due to the perceived complexity of using macros for the full QoS policy, I opted for the following architecture:

1.  **Foomuuri (`foomuuri.conf`):** Handles the firewall rules and the packet/connection marking. It sets the initial meta mark (using `mark_set -conntrack` for consistency) and copies it to the connmark (using `mark_match <mark> nft "ct mark set mark"`). This leverages Foomuuri's strength in packet filtering and marking.
    ```conf
    # Example from foomuuri.conf (e.g., internal-public zone)

    # --- BLOCK 1: SET PACKET MARK (With -conntrack) ---
    http mark_set 0x10 -conntrack
    https mark_set 0x20 -conntrack
    # ... other service marks ...
    mark_set 0xff -conntrack # Default mark

    # --- BLOCK 2: COPY PACKET MARK TO CONNMARK ---
    mark_match 0x10 nft "ct mark set mark"
    mark_match 0x20 nft "ct mark set mark"
    # ... other connmark copy rules ...
    mark_match 0xff nft "ct mark set mark" # Default connmark
    # --- END Connmark Block ---

    # Firewall accept rules follow
    http accept
    https accept
    # ...
    ```

2.  **QoS Configuration (`qos_config.yaml`):** A centralized YAML file defines the entire QoS policy: interfaces, total bandwidths, default classes, and the list of services with their corresponding mark, default upload/download HTB parameters (`class_id_suffix`, `rate`, `ceil`, `priority`, `filter_priority`), and crucially, the per-interface overrides for these parameters.
    ```yaml
    # Example from qos_config.yaml
    interfaces:
      - name: enp1s0                # WAN1 Physical Interface
        ifb: ifb_isp1              # IFB for WAN1 Download
        total_upload_bw: 50Mbit    # Actual upload capacity for enp1s0
        total_download_bw: 200Mbit # Actual download capacity for ifb_isp1
        default_upload_class: { id: "1:30", priority: 7, rate: 256kbit, ceil: 1Mbit }
        default_download_class: { id: "1:30", priority: 7, rate: 512kbit, ceil: 2Mbit }
      # ... other WAN interface definitions ...

    services:
      - mark: 0x10 # HTTP traffic
        priority: 5
        upload: # Default upload for HTTP
          class_id_suffix: "89"
          rate: 1Mbit
          ceil: 5Mbit
        download: # Default download for HTTP
          class_id_suffix: "89"
          rate: 2Mbit
          ceil: 10Mbit
        interfaces: # Overrides for HTTP on specific WANs
          enp1s0:   # Upload on WAN1
            upload: { rate: 2Mbit, ceil: 8Mbit }
          ifb_isp1: # Download on WAN1
            download: { rate: 10Mbit, ceil: 75Mbit }
      # ... other service definitions ...
    ```

3.  **Python Script (`qos_engine.py`):** Executed by Foomuuri's hooks, this script reads the YAML file, validates it, and applies all the necessary `tc` rules (HTB qdiscs, classes with correct limits based on YAML overrides, and `match mark` filters for both upload and download - using `ctinfo cpmark` for download classification).

This HTB-Duplo + Connmark approach was successfully implemented and validated.

**Discussion Point / Question:**
While the YAML + external script approach works well and provides the needed flexibility (especially for per-interface overrides), it does separate the QoS policy definition from the main `foomuuri.conf`.

My question for discussion is:

Was my assessment of the limitations of using Foomuuri macros for such a structured QoS configuration correct? 
Is there a more "Foomuuri-native" way I might have overlooked to define and manage complex, multi-interface QoS policies directly within the Foomuuri configuration files, perhaps through advanced macro usage or another mechanism? Or is the approach of using Foomuuri primarily for marking and delegating the complex `tc` setup based on an external configuration file (like YAML) considered the best practice or recommended way for advanced QoS scenarios like this? 
If this is the way to go, I would like to know if there is a way to pass foomuuri macros (or something along the lines of what shorewall has as "params") to the hook script without repeating information and thus being able to provide a cleaner way to integrate the information on foomuuri and the script, so that we could potentially drop the external YAML file and have everything defined in one single place. I tried to pass macros as arguments to the script, but without success. Another interesting approach, if foomuuri supported it, might be passing macros as environment variables, but I couldn't find any such functionality in the current version. Could I be missing something? Or could similar functionality be implemented in a future foomuuri version?

I'm sharing this to contribute my findings and learn from the community's experience. My plan is to have the final version of the script shared to everyone (foomuuri can even adopt it if you find it good enough). Any thoughts or feedback would be greatly appreciated!

Thanks!
